name: Publish package

on:
  push:
    branches: [main]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Node.JS setup
        uses: actions/setup-node@v4

      - name: Test dependencies
        working-directory: ./pkg
        run: npm ci

      - name: Test build
        working-directory: ./pkg
        run: npm run build
          
      - name: Publish to GitHub Packages registry
        working-directory: ./pkg
        run: npm publish
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}