name: Validate pull request

on:
  pull_request:
    branches: [main]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Node.JS setup
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install JQ
        run: sudo apt-get install -y jq

      - name: Validate version availability
        working-directory: pkg
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)

          if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" > /dev/null 2>&1; then
            echo "Version name is already used!"
            exit 1
          fi

      - name: Install dependencies
        working-directory: pkg
        run: npm ci

      - name: Build
        working-directory: pkg
        run: npm run build
          
      - name: Dry-publish
        working-directory: pkg
        run: npm publish --dry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}